### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by ghost** [mamsoudi/merror#2]
Hi,

is there any way to disable console output on error or use a custom logging function?

**Comment by mamsoudi** [comment]
Hi Erik,

See what merror does, is to construct a simple Error object which will then be processed by its middleware. That's why you should pass `Merror()`function which is only an error constructor to  `next()` so that it can see the error and _**only send the error in response**_. 

About your question though, sure you can always write your own error handlers. If all you want, is not to log the errors (the message with full error stack) you can see the code I wrote here:
https://repl.it/@MasoudMirzaei/ExpressErrorLogger

You can always choose what you're logging, which is also demonstrated in the link above, but you just have to uncomment line 20.

Some great explanations are available [here](https://expressjs.com/en/guide/error-handling.html) from express documentation; I think you should read them. 

Let me know if this will solve your problem.

**Comment by ghost** [comment]
Thanks for your detailed answer, it really solved my problem. But is there any way to get the properties out of the error object in the logError middleware of your example?

**Comment by mamsoudi** [comment]
I'm not sure if I understood your question, but if by "get the properties out", you mean showing more than `error.message` and `error.stack`, maybe I should extend the functionality of our error constructor which is just a simple wrapper around JS `Error()`. 

UPDATE:
---------
You already have access to all the properties in the error object. Check the list here: 
https://github.com/mamsoudi/merror/blob/master/src/merrorConstructor.ts#L34-L37
You can also see it in action here:
https://repl.it/@MasoudMirzaei/ExpressErrorLogger **(updated)**
